const novenyAdatok = {
    // SZÉNHIDRÁTOK
    "Acaciae gummi": { csoport: "Szénhidrátok", magyardrog: "Arabmézga", latin: "Acacia senegal", csalad: "Fabaceae", kep: "Acaciae_gummi.jpg", molekulak: [{nev:"arabinogalaktán"}], terapia: ["segédanyag"], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Agar": { csoport: "Szénhidrátok", magyardrog: "Agar-agar", latin: "Gelidium sesquipedale", csalad: "Gelidiaceae", kep: "Agar.jpg", molekulak: [{nev:"agaróz"}, {nev:"agaropektin}"], terapia: ["segédanyag"], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Althaeae folium": { csoport: "Szénhidrátok", magyardrog: "Orvosi ziliz levél", latin: "Althaea officinalis", csalad: "Malvaceae", kep: "Althaeae_folium.jpg", molekulak: [{nev: "nyálka"}, {nev: "keményítő"}], terapia: ["száraz köhögés"], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Althaeae radix": { csoport: "Szénhidrátok", magyardrog: "Orvosi ziliz gyökér", latin: "Althaea officinalis", csalad: "Malvaceae", kep: "Althaeae_radix.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Graminis rhizoma": { csoport: "Szénhidrátok", magyardrog: "Tarackbúza gyöktörzs", latin: "Elymus repens", csalad: "Poaceae", kep: "Graminis_rhizoma.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Lichen islandicus": { csoport: "Szénhidrátok", magyardrog: "Izlandi zuzmó", latin: "Cetraria islandica", csalad: "Parmeliaceae", kep: "Lichen_islandicus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Lini semen": { csoport: "Szénhidrátok", magyardrog: "Házi lenmag", latin: "Linum usitatissimum", csalad: "Linaceae", kep: "Lini_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Malvae folium": { csoport: "Szénhidrátok", magyardrog: "Mályvalevél", latin: "Malva sylvestris", csalad: "Malvaceae", kep: "Malvae_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Malvae sylvestris flos": { csoport: "Szénhidrátok", magyardrog: "Erdei mályva virág", latin: "Malva sylvestris", csalad: "Malvaceae", kep: "Malvae_sylvestris_flos.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Plantaginis lanceolatae folium": { csoport: "Szénhidrátok", magyardrog: "Lándzsás útifű levél", latin: "Plantago lanceolata", csalad: "Plantaginaceae", kep: "Plantaginis_lanceolatae_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Psyllii semen": { csoport: "Szénhidrátok", magyardrog: "Egyiptomi útifűmag", latin: "Plantago afra", csalad: "Plantaginaceae", kep: "Psyllii_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Salviae hispanicae semen": { csoport: "Szénhidrátok", magyardrog: "Aztékzsályamag (Chia)", latin: "Salvia hispanica", csalad: "Lamiaceae", kep: "Salviae_hispanicae_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Taraxaci officinalis radix": { csoport: "Szénhidrátok", magyardrog: "Pongyola pitypang gyökér", latin: "Taraxacum officinale", csalad: "Asteraceae", kep: "Taraxaci_officinalis_radix.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Tiliae flos": { csoport: "Szénhidrátok", magyardrog: "Hársfavirág", latin: "Tilia cordata / platyphyllos", csalad: "Malvaceae", kep: "Tiliae_flos.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Tragacantha": { csoport: "Szénhidrátok", magyardrog: "Tragakanta", latin: "Astragalus gummifer", csalad: "Fabaceae", kep: "Tragacantha.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Trigonellae foenugraeci semen": { csoport: "Szénhidrátok", magyardrog: "Görögszénamag", latin: "Trigonella foenum-graecum", csalad: "Fabaceae", kep: "Trigonellae_foenugraeci_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // ZSÍROS OLAJOK
    "Cucurbitae semen": { csoport: "Zsíros olajok", magyardrog: "Tökmag", latin: "Cucurbita pepo", csalad: "Cucurbitaceae", kep: "Cucurbitae_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Helianthi annui semen": { csoport: "Zsíros olajok", magyardrog: "Napraforgómag", latin: "Helianthus annuus", csalad: "Asteraceae", kep: "Helianthi_annui_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Papaveris semen": { csoport: "Zsíros olajok", magyardrog: "Mák", latin: "Papaver somniferum", csalad: "Papaveraceae", kep: "Papaveris_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Ricini semen": { csoport: "Zsíros olajok", magyardrog: "Ricinusmag", latin: "Ricinus communis", csalad: "Euphorbiaceae", kep: "Ricini_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Sesami semen": { csoport: "Zsíros olajok", magyardrog: "Szezámmag", latin: "Sesamum indicum", csalad: "Pedaliaceae", kep: "Sesami_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Soiae semen": { csoport: "Zsíros olajok", magyardrog: "Szójabab", latin: "Glycine max", csalad: "Fabaceae", kep: "Soiae_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // NÖVÉNYI SAVAK, KÁVÉSAVSZÁRMAZÉKOK
    "Echinaceae purpureae herba": { csoport: "Növényi savak", magyardrog: "Bíbor kasvirág virágos hajtás", latin: "Echinacea purpurea", csalad: "Asteraceae", kep: "Echinaceae_purpureae_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Equiseti herba": { csoport: "Növényi savak", magyardrog: "Mezei zsurló meddő hajtás", latin: "Equisetum arvense", csalad: "Equisetiaceae", kep: "Equiseti_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Hibisci sabdariffae flos": { csoport: "Növényi savak", magyardrog: "Szudáni hibiszkusz virágcsésze", latin: "Hibiscus sabdariffa", csalad: "Malvaceae", kep: "Hibisci_sabdariffae_flos.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Hippophaeae fructus": { csoport: "Növényi savak", magyardrog: "Homoktövis termés", latin: "Hippophae rhamnoides", csalad: "Elaeagnaceae", kep: "Hippophaeae_fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Pulmonariae folium": { csoport: "Növényi savak", magyardrog: "Orvosi tüdőfű levél", latin: "Pulmonaria officinalis", csalad: "Boraginaceae", kep: "Pulmonariae_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Rosae pseudo-fructus": { csoport: "Növényi savak", magyardrog: "Csipkebogyó (vadrózsa áltermés)", latin: "Rosa canina", csalad: "Rosaceae", kep: "Rosae_pseudo-fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Rosmarini folium": { csoport: "Növényi savak", magyardrog: "Rozmaringlevél", latin: "Rosmarinus officinalis", csalad: "Lamiaceae", kep: "Rosmarini_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // FENOLGLIKOZIDOK, KUMARINOK, LIGNÁNOK
    "Curcumae longae rhizoma": { csoport: "Fenoloidok", magyardrog: "Kurkuma gyöktörzs", latin: "Curcuma longa", csalad: "Zingiberaceae", kep: "Curcumae_longae_rhizoma.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Meliloti herba": { csoport: "Fenoloidok", magyardrog: "Orvosi somkóró virágos hajtás", latin: "Melilotus officinalis", csalad: "Fabaceae", kep: "Meliloti_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Rutae herba": { csoport: "Fenoloidok", magyardrog: "Kerti ruta virágos hajtás", latin: "Ruta graveolens", csalad: "Rutaceae", kep: "Rutae_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Schisandrae chinensis fructus": { csoport: "Fenoloidok", magyardrog: "Kínai kúszómagnélia termés", latin: "Schisandra chinensis", csalad: "Schisandraceae", kep: "Schisandrae_chinensis_fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Uvae ursi folium": { csoport: "Fenoloidok", magyardrog: "Medveszőlőlevél", latin: "Arctostaphylos uva-ursi", csalad: "Ericaceae", kep: "Uvae_ursi_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // FLAVONOIDOK
    "Aurantii amari epicarpium et mesocarpium": { csoport: "Flavonoidok", magyardrog: "Keserű narancs héj", latin: "Citrus aurantium", csalad: "Rutaceae", kep: "Aurantii_amari_epicarpium_et_mesocarpium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Betulae folium": { csoport: "Flavonoidok", magyardrog: "Nyírfalevél", latin: "Betula pendula", csalad: "Betulaceae", kep: "Betulae_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Crataegi folium cum flore": { csoport: "Flavonoidok", magyardrog: "Galagonya virágos ágvég", latin: "Crataegus monogyna", csalad: "Rosaceae", kep: "Crataegi_folium_cum_flore.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Ginkgonis folium": { csoport: "Flavonoidok", magyardrog: "Páfrányfenyő levél", latin: "Ginkgo biloba", csalad: "Ginkgoaceae", kep: "Ginkgonis_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Hyperici herba": { csoport: "Flavonoidok", magyardrog: "Orbáncfű virágos hajtás", latin: "Hypericum perforatum", csalad: "Hypericaceae", kep: "Hyperici_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Sambuci flos": { csoport: "Flavonoidok", magyardrog: "Fekete bodza virág", latin: "Sambucus nigra", csalad: "Adoxaceae", kep: "Sambuci_flos.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Silybi mariani fructus": { csoport: "Flavonoidok", magyardrog: "Máriatövis termés", latin: "Silybum marianum", csalad: "Asteraceae", kep: "Silybi_mariani_fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Solidaginis herba": { csoport: "Flavonoidok", magyardrog: "Aranyvessző virágos hajtás", latin: "Solidago virgaurea", csalad: "Asteraceae", kep: "Solidaginis_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Verbasci flos": { csoport: "Flavonoidok", magyardrog: "Ökörfarkkóró virág", latin: "Verbascum phlomoides", csalad: "Scrophulariaceae", kep: "Verbasci_flos.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // CSERZŐANYAGOK
    "Alchemillae herba": { csoport: "Cserzőanyagok", magyardrog: "Palástfű virágos hajtás", latin: "Alchemilla vulgaris", csalad: "Rosaceae", kep: "Alchemillae_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Cotini folium": { csoport: "Cserzőanyagok", magyardrog: "Cserszömörce levél", latin: "Cotinus coggygria", csalad: "Anacardiaceae", kep: "Cotini_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Quercus cortex": { csoport: "Cserzőanyagok", magyardrog: "Tölgyfakéreg", latin: "Quercus robur", csalad: "Fagaceae", kep: "Quercus_cortex.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Ratanhiae radix": { csoport: "Cserzőanyagok", magyardrog: "Ratanhia-gyökér", latin: "Krameria triandra", csalad: "Krameriaceae", kep: "Ratanhiae_radix.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // ANTRAGLIKOZIDOK
    "Aloe capensis": { csoport: "Antraglikozidok", magyardrog: "Fokföldi aloé", latin: "Aloe ferox", csalad: "Asphodelaceae", kep: "Aloe_capensis.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Frangulae cortex": { csoport: "Antraglikozidok", magyardrog: "Kutyabengekéreg", latin: "Frangula alnus", csalad: "Rhamnaceae", kep: "Frangulae_cortex.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Sennae foliolum": { csoport: "Antraglikozidok", magyardrog: "Szenalevél", latin: "Cassia senna", csalad: "Fabaceae", kep: "Sennae_foliolum.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Sennae fructus": { csoport: "Antraglikozidok", magyardrog: "Szenatermés", latin: "Cassia angustifolia", csalad: "Fabaceae", kep: "Sennae_fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // TERPENOFENOLOIDOK
    "Cannabis herba": { csoport: "Terpenofenoloidok", magyardrog: "Kender virágos hajtás", latin: "Cannabis sativa", csalad: "Cannabaceae", kep: "Cannabis_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Lupuli flos": { csoport: "Terpenofenoloidok", magyardrog: "Komlótoboz", latin: "Humulus lupulus", csalad: "Cannabaceae", kep: "Lupuli_flos.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // ILLÓOLAJOK
    "Absinthii herba": { csoport: "Illóolajok", magyardrog: "Fehér üröm virágos hajtás", latin: "Artemisia absinthium", csalad: "Asteraceae", kep: "Absinthii_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Anisi fructus": { csoport: "Illóolajok", magyardrog: "Ánizstermés", latin: "Pimpinella anisum", csalad: "Apiaceae", kep: "Anisi_fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Carvi fructus": { csoport: "Illóolajok", magyardrog: "Konyhakömény termés", latin: "Carum carvi", csalad: "Apiaceae", kep: "Carvi_fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Caryophylli flos": { csoport: "Illóolajok", magyardrog: "Szegfűszeg", latin: "Syzygium aromaticum", csalad: "Myrtaceae", kep: "Caryophylli_flos.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Cinnamomi cortex": { csoport: "Illóolajok", magyardrog: "Fahéjfa kéreg", latin: "Cinnamomum verum", csalad: "Lauraceae", kep: "Cinnamomi_cortex.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Coriandri fructus": { csoport: "Illóolajok", magyardrog: "Koriandertermés", latin: "Coriandrum sativum", csalad: "Apiaceae", kep: "Coriandri_fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Foeniculi dulcis fructus": { csoport: "Illóolajok", magyardrog: "Édeskömény termés", latin: "Foeniculum vulgare var. dulce", csalad: "Apiaceae", kep: "Foeniculi_dulcis_fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Juniperi galbulus": { csoport: "Illóolajok", magyardrog: "Borókabogyó", latin: "Juniperus communis", csalad: "Cupressaceae", kep: "Juniperi_galbulus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Lavandulae flos": { csoport: "Illóolajok", magyardrog: "Levendulavirág", latin: "Lavandula angustifolia", csalad: "Lamiaceae", kep: "Lavandulae_flos.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Matricariae flos": { csoport: "Illóolajok", magyardrog: "Kamillavirágzat", latin: "Matricaria recutita", csalad: "Asteraceae", kep: "Matricariae_flos.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Menthae crispae folium": { csoport: "Illóolajok", magyardrog: "Fodormentalevél", latin: "Mentha spicata var. crispa", csalad: "Lamiaceae", kep: "Menthae_crispae_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Menthae piperitae folium": { csoport: "Illóolajok", magyardrog: "Borsmentalevél", latin: "Mentha x piperita", csalad: "Lamiaceae", kep: "Menthae_piperitae_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Millefolii herba": { csoport: "Illóolajok", magyardrog: "Cickafark virágos hajtás", latin: "Achillea millefolium", csalad: "Asteraceae", kep: "Millefolii_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Salviae officinalis folium": { csoport: "Illóolajok", magyardrog: "Orvosi zsálya levél", latin: "Salvia officinalis", csalad: "Lamiaceae", kep: "Salviae_officinalis_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Thymi herba": { csoport: "Illóolajok", magyardrog: "Kakukkfű virágos hajtás", latin: "Thymus vulgaris", csalad: "Lamiaceae", kep: "Thymi_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // KESERŰANYAGOK, IRIDOIDOK
    "Cardui benedicti herba": { csoport: "Keserűanyagok", magyardrog: "Benedekfű virágos hajtás", latin: "Centaurea benedicta", csalad: "Asteraceae", kep: "Cardui_benedicti_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Centaurii herba": { csoport: "Keserűanyagok", magyardrog: "Kis ezerjófű virágos hajtás", latin: "Centaurium erythraea", csalad: "Gentianaceae", kep: "Centaurii_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Gentianae radix": { csoport: "Keserűanyagok", magyardrog: "Tárnicsgyökér", latin: "Gentiana lutea", csalad: "Gentianaceae", kep: "Gentianae_radix.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Valerianae radix": { csoport: "Keserűanyagok", magyardrog: "Macskagyökér", latin: "Valeriana officinalis", csalad: "Caprifoliaceae", kep: "Valerianae_radix.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // TRITERPÉNSZÁRMAZÉKOK
    "Calendulae flos": { csoport: "Triterpének", magyardrog: "Körömvirág", latin: "Calendula officinalis", csalad: "Asteraceae", kep: "Calendulae_flos.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Convallariae folium": { csoport: "Triterpének", magyardrog: "Gyöngyviráglevél", latin: "Convallaria majalis", csalad: "Asparagaceae", kep: "Convallariae_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Digitalis lanatae folium": { csoport: "Triterpének", magyardrog: "Gyapjas gyűszűvirág levél", latin: "Digitalis lanata", csalad: "Plantaginaceae", kep: "Digitalis_lanatae_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Ginseng radix": { csoport: "Triterpének", magyardrog: "Ginzenggyökér", latin: "Panax ginseng", csalad: "Araliaceae", kep: "Ginseng_radix.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Hederae folium": { csoport: "Triterpének", magyardrog: "Borostyánlevél", latin: "Hedera helix", csalad: "Araliaceae", kep: "Hederae_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Hippocastani semen": { csoport: "Triterpének", magyardrog: "Vadgesztenyemag", latin: "Aesculus hippocastanum", csalad: "Sapindaceae", kep: "Hippocastani_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Liquiritiae radix": { csoport: "Triterpének", magyardrog: "Édesgyökér", latin: "Glycyrrhiza glabra", csalad: "Fabaceae", kep: "Liquiritiae_radix.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Strophanthi semen": { csoport: "Triterpének", magyardrog: "Sztrófanthuszmag", latin: "Strophanthus kombe", csalad: "Apocynaceae", kep: "Strophanthi_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },

    // ALKALOIDOK
    "Belladonnae folium": { csoport: "Alkaloidok", magyardrog: "Nadragulyalevél", latin: "Atropa belladonna", csalad: "Solanaceae", kep: "Belladonnae_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Stramonii folium": { csoport: "Alkaloidok", magyardrog: "Csattanó maszlag levél", latin: "Datura stramonium", csalad: "Solanaceae", kep: "Stramonii_folium.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Chelidonii herba": { csoport: "Alkaloidok", magyardrog: "Fecskefű virágos hajtás", latin: "Chelidonium majus", csalad: "Papaveraceae", kep: "Chelidonii_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Cinchonae cortex": { csoport: "Alkaloidok", magyardrog: "Kínafakéreg", latin: "Cinchona pubescens", csalad: "Rubiaceae", kep: "Cinchonae_cortex.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Ipecacuanhae radix": { csoport: "Alkaloidok", magyardrog: "Hánytatógyökér", latin: "Carapichea ipecacuanha", csalad: "Rubiaceae", kep: "Ipecacuanhae_radix.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Papaveris maturi fructus": { csoport: "Alkaloidok", magyardrog: "Mák (termésfal)", latin: "Papaver somniferum", csalad: "Papaveraceae", kep: "Papaveris_maturi_fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Secale cornutum": { csoport: "Alkaloidok", magyardrog: "Anyarozs", latin: "Claviceps purpurea", csalad: "Clavicipitaceae", kep: "Secale_cornutum.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Strychni semen": { csoport: "Alkaloidok", magyardrog: "Ebvészmag", latin: "Strychnos nux-vomica", csalad: "Loganiaceae", kep: "Strychni_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Vincae minoris herba": { csoport: "Alkaloidok", magyardrog: "Kis télizöld virágos hajtás", latin: "Vinca minor", csalad: "Apocynaceae", kep: "Vincae_minoris_herba.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Camelliae sinensis non fermentata folia": { csoport: "Alkaloidok", magyardrog: "Zöld tea levél", latin: "Camellia sinensis", csalad: "Theaceae", kep: "Camelliae_sinensis_non_fermentata_folia.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Capsici fructus": { csoport: "Alkaloidok", magyardrog: "Paprikatermés", latin: "Capsicum annuum", csalad: "Solanaceae", kep: "Capsici_fructus.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Coffeae semen": { csoport: "Alkaloidok", magyardrog: "Kávémag", latin: "Coffea arabica", csalad: "Rubiaceae", kep: "Coffeae_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Colae semen": { csoport: "Alkaloidok", magyardrog: "Kólamag", latin: "Cola nitida", csalad: "Malvaceae", kep: "Colae_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } },
    "Colchici semen": { csoport: "Alkaloidok", magyardrog: "Őszi kikerics mag", latin: "Colchicum autumnale", csalad: "Colchicaceae", kep: "Colchici_semen.jpg", molekulak: [], terapia: [], kvalitativ: [], kvantitativ: { kep: "", meghatarozasok: [] } }
};
